# Generated by Django 5.1.6 on 2025-02-19 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_reservation_name_review_name_alter_reservation_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='favorite_by',
            field=models.ManyToManyField(related_name='favorite_resorts', to=settings.AUTH_USER_MODEL),
        ),
    ]
